Improve setup

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -31,4 +31,6 @@ if [[ ! -d ./tmp/postgres ]]; then
   initdb './tmp/postgres' -E utf8 --locale en_US
 fi
 
+type npm >/dev/null 2>&1 || { echo >&2 "I require npm but it's not installed.  Aborting."; exit 1; }
+
 npm install
